CREATE TABLE TTABLE 
(
  PK NUMBER NOT NULL 
, CBOOL NUMBER(1) 
, CINT NUMBER
, CFLOAT FLOAT
, CNUMERIC NUMBER(10, 4) 
, CSTRING NVARCHAR2(100) 
, CDATETIME DATE
, CGUID RAW(16)  
, CBYTES BLOB
, CONSTRAINT TTABLE_PK PRIMARY KEY 
  (
    PK 
  )
) 
;

CREATE SEQUENCE TTABLE_PK_Sequence INCREMENT BY 1 START WITH 1 NOMAXVALUE NOCYCLE CACHE 10;

CREATE TRIGGER TTABLE_PK_Identity BEFORE INSERT ON  TTABLE FOR EACH ROW WHEN (new.PK is null)
begin
select TTABLE_PK_Sequence.nextval into:new.PK from dual;
end;
